### ISSUE TITLE
[JOSS Review] MAINT: Add a PyPI installation option

### ISSUE THREAD

**Issue by imtambovtcev** [BattModels/asimtools#44]
The installation instructions are clear; however, adding a PyPI installation option would be a valuable enhancement and improve accessibility for users.

[This suggestion is part of my review in the JOSS submission](https://github.com/openjournals/joss-reviews/issues/7085).

**Comment by mkphuthi** [comment]
Hi, Thanks for the suggestion. A PyPi installation option has been added and can be found at [](https://pypi.org/project/asimtools/0.0.0/)
