### ISSUE TITLE
[JOSS Review] DOC: Emphasize ASIMTools advantages over existing solutions

### ISSUE THREAD

**Issue by imtambovtcev** [BattModels/asimtools#45]
The paper outlines the capabilities of ASIMTools well, but it would be helpful to further emphasize the specific advantages of this tool over existing solutions. Clarifying what unique contributions ASIMTools offers compared to what already exists would strengthen the documentation. This could involve a more direct explanation of how ASIMTools enhances current workflows and addresses challenges that other tools may not fully resolve.

[This suggestion is part of my review in the JOSS submission](https://github.com/openjournals/joss-reviews/issues/7085).

**Comment by mkphuthi** [comment]
Dear @imtambovtcev ,

We tried to address this in the paper in the statement of need section: 

> There is however no unifying framework that can
> encompass all these tools without significant software development effort.
> Significant effort should not be necessary because while the source of the
> fundamental outputs of atomistic potentials such as energy, forces etc. may
> differ, simulation protocols built on these outputs should converge towards the
> most accurate and computationally efficient. ASIMTools focuses on this last
> aspect by introducing asimmodules which are simply Python functions that act as
> simulation protocols which have no dependence on a specific atomistic potential
> or computational environment or atomic structure.

Is the suggestion that we rephrase more clearly or that we cite other works or that we include this in the docs? Some clarity would be helpful

Thanks.

**Comment by imtambovtcev** [comment]
Dear @mkphuthi,

Thank you for your response. One way to further clarify the advantages of ASIMTools could be to include an example in the documentation that outlines a common problem in atomic simulations and demonstrates how ASIMTools provides a solution. A "problem and solution" format might help illustrate its unique contributions more concretely.

If this approach works for you, it could be a helpful addition.

Best regards,
@imtambovtcev

**Comment by mkphuthi** [comment]
Great. I understand now. I have edited the ReadMe to point immediately to the [Developing Custom Asimmodules](https://eeg.engin.umich.edu/asimtools/asimplify.html) page where I have tried to make clear the advantages of using ASIMTools over the traditional approach in a problem-solution structure.

@mkphuthi
