### ISSUE TITLE
[JOSS REVIEW] Please make a release

### ISSUE THREAD

**Issue by HaoZeke** [BattModels/asimtools#50]
Part of https://github.com/openjournals/joss-reviews/issues/7085

I see there is a PyPI version, but it is set at v0.0.0

Please:
- Make a new tag (v0.0.1 perhaps)
- Make a release
- Upload to PyPI

Additionally, for JOSS we will need to have a Zenodo archive of this version as well (to be set as the version of record).

**Comment by mkphuthi** [comment]
Hi @HaoZeke 

I've made the suggested changes. See:

Release: https://github.com/BattModels/asimtools/releases/tag/v0.0.1
PyPI distribution: https://pypi.org/manage/project/asimtools/release/0.0.1/
Zenodo archive: https://zenodo.org/records/13942780

Let me know if there is anything else necessary.

**Comment by HaoZeke** [comment]
Thanks, that should be all for this issue.
